34 create game mechanism
ilinaro/GROK pull request #18
Opened 2023-07-04 02:00 UTC by ilinaro

### Какую задачу решаем
**Создать механику игры на Canvas API**
Сейчас там могут быть серые прямоугольники без красивых картинок. Главная задача — сделать так, чтобы можно было управлять персонажами, картами или другими элементами, которые у вас используются. Примеры компонентов: 1. Луп игры. Мы должны создать бесконечный цикл, который обновляет состояние игры и перерисовывает экран каждый кадр. В цикле игры мы должны обрабатывать ввод от пользователя, обновлять состояние игры и перерисовывать экран. 2. Обработка событий клавиш. Для управления состоянием игры и персонажей необходимо обрабатывать ввод от клавиатуры. Это может быть сделано с помощью событий клавиатуры, таких как "keydown" и "keyup", которые отслеживают, когда клавиши нажимаются и отпускаются. 3. Рисование объектов на Canvas, таких как фон, персонажи, враги и другие элементы игры. Это можно сделать с помощью методов Canvas API, таких как fillRect(), strokeRect(), drawImage() и другие. 4. Обнаружение столкновений. В игре может быть необходимо обнаруживать столкновения между персонажами и объектами, например, столкновение с врагами или препятствиями. Можно реализовать это с помощью метода intersects() для определения пересечения двух прямоугольников. 5. Анимация: мы можем создавать анимированных персонажей и объекты, используя методы Canvas API, такие как requestAnimationFrame() и setIn

terval(). Мы можем также использовать спрайты для создания анимации и изменения состояния объектов в игре. Это основные элементы, которые мы можем реализовать в игре на Canvas API. Детали могут отличаться в зависимости от конкретной игры, но эти элементы могут служить основой для любой игры на Canvas API.
### Скриншоты/видяшка (если есть)

https://github.com/ilinaro/GROK/assets/87081323/9df3b351-1fc4-4a14-af06-88c281d2c3cd
https://github.com/ilinaro/GROK/assets/87081323/a2409bea-9e12-4b96-9333-c4ddd822671c
![Снимок экрана 2023-07-04 в 04 58 57](https://github.com/ilinaro/GROK/assets/87081323/c4c37075-a820-4eb1-a664-585ff86e37a1)
![Снимок экрана 2023-07-04 в 04 59 49](https://github.com/ilinaro/GROK/assets/87081323/a38e6b2a-a5a8-4ead-920c-d5bd7280ea89)
![Снимок экрана 2023-07-04 в 04 59 29](https://github.com/ilinaro/GROK/assets/87081323/e6e254d6-c257-428d-92be-9c4c022439b8)

2023-07-04 16:03 UTC, Olegas requested changes
Есть критичные замечания к реализации, нужно доработать

2023-07-04 16:03 UTC, Olegas commented on packages/client/src/fuature/game/scene/SceneCanvas.ts
>        window.removeEventListener('resize', () => {
Эта отписка не будет работать, потому что вы создали новую функцию (пусть даже и выглядит она как та, что подписали) и пытаетесь ее отписать. Отписывать надо буквально ту же самую функцию, что была добавлена как обработчик

2023-07-05 06:53 UTC, ilinaro commented on packages/client/src/fuature/game/scene/Player.ts
> +type PlayerT = {
https://github.com/ilinaro/GROK/pull/19

2023-07-05 06:53 UTC, ilinaro commented on packages/client/src/fuature/game/scene/SceneCanvas.ts
> +    ball.onload;
https://github.com/ilinaro/GROK/pull/19

2023-07-05 06:53 UTC, ilinaro commented on packages/client/src/fuature/game/scene/SceneCanvas.ts
> +      ball.onload;
https://github.com/ilinaro/GROK/pull/19

2023-07-05 06:53 UTC, ilinaro commented on packages/client/src/fuature/game/scene/SceneCanvas.ts
> +  }
https://github.com/ilinaro/GROK/pull/19

2023-07-05 06:53 UTC, ilinaro commented on packages/client/src/fuature/game/scene/SceneCanvas.ts
>        window.removeEventListener('resize', () => {
https://github.com/ilinaro/GROK/pull/19

2023-07-05 06:53 UTC, ilinaro commented
https://github.com/ilinaro/GROK/pull/19

2023-07-05 17:11 UTC, Olegas approved these changes

2023-07-06 08:24 UTC, closed without merging