Remotes/origin/27 mf2 45
ilinaro/GROK pull request #34
Opened 2023-07-14 22:02 UTC by err415

### Какую задачу решаем
Добавить минимум одно Web API
- FullScreen

### Скриншоты/видяшка (если есть)
![image](https://github.com/ilinaro/GROK/assets/117043822/8e500eb2-a379-47e9-9111-5b23f77e52f5)
![image](https://github.com/ilinaro/GROK/assets/117043822/f606e263-7e65-4c28-b914-a463bd487a01)

2023-07-14 22:10 UTC, AlexSm0ke approved these changes
Все гуд

2023-07-15 08:55 UTC, IvanPeleshok commented on packages/client/src/fuature/forum/components/CreateForm/CreateForm.tsx
> +  const createTopic = (e: any) => {
Просьба типизировать здесь и ниже параметры функции
```
React.ChangeEvent<HTMLInputElement>
```

2023-07-15 08:55 UTC, IvanPeleshok commented on packages/client/src/fuature/forum/components/answers/AnswerElements/AnswerElements.tsx
> +
Лишний отступ

2023-07-15 08:57 UTC, IvanPeleshok commented on packages/client/src/fuature/forum/components/answers/AnswerItem/AnswerItem.tsx
> +  answers: Record<string, string>;
Есть ли возможность описать интерфейс answers более подробно?
```
answers: {
  desc: string
  titiel: string
 и т.д
}
```

2023-07-15 08:57 UTC, IvanPeleshok commented on packages/client/src/fuature/forum/components/answers/Answers.tsx
> +export const ForumAnswers:React.FC = () => {
Не хватает пробела после ":"

2023-07-15 08:58 UTC, IvanPeleshok commented on packages/client/src/fuature/forum/components/fullscreen/FullScreen.tsx
> +function eventHandler(event: HTMLButtonElement | MouseEvent) {
Просьба писать обработчик в рамках компонента (в данном случае, FullScreen)
Для оптимизации предлагаю воспользоваться useCallback (если есть желание)
https://react.dev/reference/react/useCallback

2023-07-15 08:59 UTC, IvanPeleshok commented on packages/client/src/fuature/forum/components/fullscreen/FullScreen.tsx
> +    document
Переписать на async / await + try / catch
https://learn.javascript.ru/async-await
Пользуемся последними возможностями языка

2023-07-15 09:00 UTC, IvanPeleshok commented on packages/client/src/fuature/forum/components/fullscreen/FullScreen.tsx
> +    <button type='submit' id='toggler' onClick={(e) => { eventHandler(e)}} className={ styles.iconNotification }></button>
Необязательно передавать инлайн колбеки, достаточно передать ссылку на метод
```
<div onClick={handleClick} />
```

2023-07-15 09:03 UTC, IvanPeleshok requested changes
Есть замечания

2023-07-15 09:15 UTC, IvanPeleshok commented on packages/client/src/fuature/forum/Forum.module.scss
> +
Так и предполагалось?

2023-07-15 19:47 UTC, IvanPeleshok commented on packages/client/src/fuature/forum/components/answers/AnswerItem/AnswerItem.tsx
> +    props: {}
Что за поле props у answers?
Есть возможность описать его?
По всей видимости он не используется в файле
Можно убрать

2023-07-15 19:48 UTC, IvanPeleshok commented on packages/client/src/fuature/forum/components/fullscreen/FullScreen.module.scss
> +}
Не хватает отступа (пустая строка)

2023-07-15 19:52 UTC, IvanPeleshok commented on packages/client/src/fuature/forum/components/fullscreen/FullScreen.tsx
> +      await document
Видимо не совсем был мой комментарий
https://learn.javascript.ru/async-await
Если зайдёте в доку, которую я скинул, то будет ясно, что можно писать что-то такое:
```
try {
  await document.exitFullscreen()
  event.target as HTMLDivElement).classList.remove( styles.fullScreenActive)
} catch (err) {
  throw new Error(err)
}
```

Это решает проблему колбеков 
[Адская пирамида вызовов](https://learn.javascript.ru/callbacks#adskaya-piramida-vyzovov)

2023-07-15 19:56 UTC, IvanPeleshok commented on packages/client/src/fuature/forum/components/fullscreen/FullScreen.tsx
> +          (event.target as HTMLDivElement).classList.remove( styles.fullScreenActive)
В реаке мы не работаем через дом ноды, т.к это влияет на производительность
Предлагаю завести переменную, которая будет за это отвечать и уже на её основании добавлять классы с помощью classNames
```
const [isFullscreeen, setFullscreen] = setState(false)

const eventHandler = () => {
  по какой-то логике выставляем через setFullscreen(true или false)
}

return (
  <button className={classNames(styles.iconFullScreen, {
     [styles.fullScreenActive]: isFullscreeen
  })}
)
```

2023-07-15 19:57 UTC, IvanPeleshok commented on packages/client/src/fuature/forum/components/fullscreen/FullScreen.tsx
> +      await document.documentElement.requestFullscreen().then(r => {
Аналогично комменту выше

2023-07-15 19:58 UTC, IvanPeleshok requested changes
Есть замечания

2023-07-15 22:01 UTC, IvanPeleshok commented on packages/client/src/fuature/forum/components/fullscreen/FullScreen.tsx
> +    } else {
Рекомендация: пытаться оставлять структуру линейной, без ветвлений
```
if () {
  ...
  
  return
}

// else 
```

2023-07-15 22:02 UTC, IvanPeleshok commented on packages/client/src/fuature/forum/components/fullscreen/FullScreen.tsx
> +    <button className={classNames(styles.iconFullScreen, {
Рекомендация: писать пропсы со смещением на каждую строку
```
<Component props1={prop1}
  props2={prop2}
/>
```

2023-07-15 22:03 UTC, IvanPeleshok commented on packages/client/src/fuature/forum/components/fullscreen/FullScreen.tsx
> +    })} type='submit' id='toggler' onClick={(e) => eventHandler(e)}></button>
Рекомендация: если сигнатура вызова совпадает, то лучше передавать ссылку, а не дописывать callback

2023-07-15 22:03 UTC, IvanPeleshok approved these changes

2023-07-16 07:44 UTC, merged