40 logic game
ilinaro/GROK pull request #38
Opened 2023-07-16 22:38 UTC by ilinaro

### Какую задачу решаем:
Реализовать одну из игровых механик, описанных в документе с логикой игры

Результат:
Движение по лабиринту, управление (чтобы прыгнуть нужно нажать 2 раз на пробел чтобы подпрыгнуть выше - трудность)
Отрисована часть карты и движение по ней, с учетом блоком столкновений

### Скриншоты/видяшка (если есть)
<img width="1710" alt="Снимок экрана 2023-07-17 в 01 35 11" src="https://github.com/ilinaro/GROK/assets/87081323/10d4fe26-ffa5-485d-8730-6c6b65858f0b">

2023-07-17 12:42 UTC, IvanPeleshok commented on packages/client/src/fuature/game/data/source.ts
> +];
Рекомендация оставить пустую строку в конце файла и вот почему: https://translated.turbopages.org/proxy_u/en-ru.ru.76eb1502-64b5373f-d2d6c468-74722d776562/https/stackoverflow.com/questions/2287967/why-is-it-recommended-to-have-empty-line-in-the-end-of-a-source-file

2023-07-17 12:43 UTC, IvanPeleshok commented on packages/client/src/fuature/game/scene/Events.ts
> +  };
Не хватает отступов (предлагаю отделять сущности методов и переменных)

2023-07-17 12:44 UTC, IvanPeleshok commented on packages/client/src/fuature/game/scene/Events.ts
> +      case 'w':
Вынести клавиши в enum Keyboard Key: w / ArrowUp и т.д
Сможем потом переиспользовать где-нибудь ещё

2023-07-17 13:26 UTC, IvanPeleshok commented on packages/client/src/fuature/game/scene/Sprite.ts
> +    // this.context.clearRect(this.position.x, this.position.y, this.position.width, this.position.height);
Если не используем, то предлагаю выпилить

2023-07-17 13:29 UTC, IvanPeleshok commented on packages/client/src/fuature/profile/Profile.tsx
> +      {modes[mode]}
Идея интересная, но нагляднее будет просто в JSX отобразить компоненты и отображать их по условиям, относительно `mode`

2023-07-17 13:30 UTC, IvanPeleshok commented on packages/client/src/fuature/profile/components/avatar-input/style.module.scss
> +        display: none;
Что-то не то с форматированием файла (ранее отступ был в два пробела)

2023-07-17 13:31 UTC, IvanPeleshok commented on packages/client/src/fuature/profile/components/button/button.tsx
> +  onClick(e: Event): void;
Неправильный тип
```
onClick(e: React.MouseEvent<HTMLButtonElement>): void
```

2023-07-17 13:32 UTC, IvanPeleshok commented on packages/client/src/fuature/profile/components/change-password-form/change-password.tsx
> +    changePassword({ oldPassword: old_password, newPassword: new_password })
async / await (не используем колбеки then / catch)

2023-07-17 13:33 UTC, IvanPeleshok commented on packages/client/src/fuature/profile/components/change-password-form/change-password.tsx
> +        return window.location.reload();
У вас не подключен react-router-domr?

2023-07-17 13:34 UTC, IvanPeleshok commented on packages/client/src/fuature/profile/components/change-password-form/change-password.tsx
> +  old_password: boolean;
Переменные именуем без _
oldPassword

2023-07-17 13:35 UTC, IvanPeleshok commented on packages/client/src/fuature/profile/components/input/style.module.scss
> +	width: 100%;
Форматирование

2023-07-17 13:36 UTC, IvanPeleshok requested changes
Есть замечания

2023-07-18 12:32 UTC, ilinaro commented on packages/client/src/fuature/game/scene/Sprite.ts
> +    // this.context.clearRect(this.position.x, this.position.y, this.position.width, this.position.height);
будет переиспользоваться для других элементов

2023-07-18 12:37 UTC, ilinaro commented on packages/client/src/fuature/profile/components/button/button.tsx
> +  onClick(e: Event): void;
Профиль я не трогал, это не моя реализация. Поправил

2023-07-18 12:37 UTC, ilinaro commented on packages/client/src/fuature/profile/components/change-password-form/change-password.tsx
> +        return window.location.reload();
Это тоже не мой код. Поправил

2023-07-18 12:37 UTC, ilinaro commented on packages/client/src/fuature/profile/components/change-password-form/change-password.tsx
> +  old_password: boolean;
Это не моя реализация, поправил

2023-07-18 12:38 UTC, ilinaro commented on packages/client/src/fuature/profile/components/input/style.module.scss
> +	width: 100%;
Это не моя реализация, поправил

2023-07-18 12:39 UTC, ilinaro commented on packages/client/src/fuature/profile/components/change-password-form/change-password.tsx
> +  old_password: boolean;
Я прекрасно понимаю что так нельзя, это не я писал

2023-07-18 12:47 UTC, ilinaro commented on packages/client/src/fuature/game/scene/Sprite.ts
> +    // this.context.clearRect(this.position.x, this.position.y, this.position.width, this.position.height);
Пока нужно оставить

2023-07-18 19:40 UTC, IvanPeleshok approved these changes

2023-07-19 14:23 UTC, closed without merging