27 mf2 52
ilinaro/GROK pull request #44
Opened 2023-07-26 00:29 UTC by err415

### Какую задачу решаем
Добавить ещё одно WEB API (кроме Canvas, Fetch) - 27 mf2 52

### Скриншоты/видяшка (если есть)
![image](https://github.com/ilinaro/GROK/assets/117043822/167b0ab0-b824-42f7-a060-ce45f020e335)
![image](https://github.com/ilinaro/GROK/assets/117043822/565b30bb-c421-46e3-b0a4-384b9cccd411)
![image](https://github.com/ilinaro/GROK/assets/117043822/0acd3a44-4a9f-4cad-93b7-0c6f0d341651)
![image](https://github.com/ilinaro/GROK/assets/117043822/fe2af940-5555-4c78-8eca-063abdeed654)

2023-07-27 00:45 UTC, bin-umar requested changes
Привет! Я ревьеюр из Я.Практикума.

Хорошо что решили попробовать ещё один браузерный API, но не вижу хотя бы одного примера где происходит реальная нотификация. Вы сделали просто компоненты для кастомного [тоастера](https://mui.com/material-ui/react-snackbar/#customization), который не связан с Notification API. А часть связанный с Notification API просто включает его (ну или спрашивает пользователя включить ли нотификации?).

Прощу починить мелкие замечания оставленные ниже. А дизайн токены можете обсудить с командой и сделать отдельной задачей (рекомендую).

Также, приведите пример гипотетического кейса в котором в будущем будете слать реальные уведомления.

2023-07-27 00:45 UTC, bin-umar commented on packages/client/src/fuature/forum/components/notification/components/AlertButton/index.ts
Empty file, для чего он нужен?

2023-07-27 00:45 UTC, bin-umar commented on packages/client/src/fuature/forum/components/notification/components/AlertButton/AlertButton.tsx
> +  type: string;
Лучше типизировать тип:
```suggestion
  type: 'success' | 'error';
```

2023-07-27 00:45 UTC, bin-umar commented on packages/client/src/fuature/forum/components/notification/components/AlertButton/AlertButton.module.scss
> +.btn__action_no {
```suggestion
.btn__action_cancel {
```

2023-07-27 00:45 UTC, bin-umar commented on packages/client/src/fuature/forum/components/notification/components/AlertButton/AlertButton.tsx
> +        [styles.btn__action_no]: type === "unsuccess"
вместо unsucces привычнее использовать 'error'

2023-07-27 00:45 UTC, bin-umar commented on packages/client/src/fuature/forum/components/notification/components/AlertButton/AlertButton.tsx
> +type AlertButtonT = {
Нет необходимости добавлять в конце типов 'T'

2023-07-27 00:45 UTC, bin-umar commented on packages/client/src/fuature/forum/components/notification/Notification.tsx
> +    }
Добавь, пожалуйста, форматирование, без этого сложно читается

2023-07-27 00:45 UTC, bin-umar commented on packages/client/src/fuature/forum/components/notification/Notification.tsx
> +    await Notification.requestPermission().then((permission) => {
Странно что ты делаешь и await и then. Надо делать либо одно, либо другое. Современнее делать это с await-ом

2023-07-27 00:45 UTC, bin-umar commented on packages/client/src/fuature/forum/components/notification/Notification.tsx
> +    const notification = new Notification(notificationText);
Кажется достаточно просто 
```suggestion
new Notification(notificationText);
```
так как ты не используешь ниже переменную notification.

2023-07-27 00:45 UTC, bin-umar commented on packages/client/src/fuature/forum/components/notification/Notification.tsx
> +    await notify().then(() => {
Тоже самое, либо await, либо then

2023-07-27 00:45 UTC, bin-umar commented on packages/client/src/fuature/forum/components/notification/Notification.tsx
> +          <AlertButton type="success" onClick={ enableNotifyAndClose }>Конечно!</AlertButton>
С точки зрения UX не очень понятно о чём идёт речь, так как нет вопроса.

Ты: Уведомления выключены!
Я: Конечно!

А, ожидаемый результат-то что?)

Я: Нет, спасибо! (А что вообще происходит?)))

2023-07-27 00:45 UTC, bin-umar commented on packages/client/src/fuature/forum/components/notification/Notification.tsx
> +  ) :
Лучше добавить отдельные условия так как такой тернарник сложно читается и усложняет когнитивное восприятие кода.

```suggestion
if (!(userResponded) && !(Notification.permission === "granted")) {
   return (
   <Alert type="success">
     <AlertIcon type="success" />
     <Box>
       <AlertTitle>Уведомления</AlertTitle>
       <AlertDesc>Включить уведомления?</AlertDesc>
     </Box>
     <div className={ styles.notification__button }>
     <AlertButton type="success" onClick={ enableNotifyAndClose }>Конечно!</AlertButton>
     <AlertButton type="unsuccess" onClick={ disableNotifyAndClose }>Нет, спасибо!</AlertButton>
     </div>
   </Alert>
   );
}

if (Notification.permission === "granted") {
    return (
         <AlertButton type="success" onClick={ () => notify("Уведомления успешно подключены!") }>Нажми, чтобы увидеть!</AlertButton>
     );
}
```

2023-07-27 00:45 UTC, bin-umar commented on packages/client/src/fuature/forum/components/notification/components/Alert/Alert.module.scss
> +  color: #0a0a0a;
Надо вынести все цвета в дизайн токены (css/sass переменные).
Основной смысл этих переменных это выделение цветов в дизайн-токены. А смысл дизайн токенов в том чтобы в случае редизайна или изменения конкретного значения токена изменился бы в одном месте.
Стоит помнить задача состоит не в том чтобы все белые цвета перевести в одну переменную, черные во вторую, и т.д. Потому что например мы можем использовать белый цвет как background, так и в качестве цвет текста основного наших кнопок. В таком случае совершенно валидно и правильно разделить их в две разные переменные:
- colorBg
- colorButtonText

Иными словами не стоит группировать по значению, так как это бессмысленно, а надо по css свойствам.

В качестве примера можешь посмотреть https://paradigm.mail.ru/design_tokens/colors, можешь на его примере убедиться что белый цвет например используется в трёх разных токенах.

2023-07-27 00:45 UTC, bin-umar commented on packages/client/src/fuature/forum/components/notification/components/AlertDesc/AlertDesc.tsx
Декомпозиция это конечно хорошо, но не стоит настолько сильно декомпозировать компоненты. Потому что вырастает количество файлов с короткими содержимыми и может усложнить чтению кода. А одна из задач декомпозиции это как раз таки упрощение. Другая задача это переиспользуемость компонента, но в данном случае эти мелкие компоненты привязаны к родительскому компоненту и не могут самостоятельно использоваться (или могут, но семантически будет неправильно). Поэтому их лучше объединить в родительский компонент, либо как минимум перенести в родительскую директорию чтобы было понятно что это дочерние компоненты компонента Alert.

2023-07-27 00:45 UTC, bin-umar commented on packages/client/src/fuature/forum/components/notification/components/AlertIcon/AlertIcon.module.scss
> +  margin: 50% auto;
задача состоит в том чтобы его централизировать?

2023-07-28 06:22 UTC, bin-umar commented
@err415 Подскажи плиз, все ли комментарии пофикшены?

2023-08-09 09:46 UTC, bin-umar commented on packages/client/src/fuature/forum/components/notification/Notification.tsx
> +          await Notification.requestPermission().then((permission) => {
Всё ещё вижу await с then-ом. Это две разные подходы обработки асинхронних функций, прощу оставить либо одно, либо второе.

2023-08-09 09:48 UTC, bin-umar commented on packages/client/src/fuature/forum/components/notification/components/Alert/Alert.tsx
> +  })
Что делает этот useEffect?

2023-08-09 09:51 UTC, bin-umar commented on packages/client/src/fuature/forum/components/notification/components/Alert/Alert.tsx
> +        <div className={ styles.close_btn } onClick={ () => !isActive }></div>
Изменение props-а ничего не значит, компоненты бывают либо умными (у которых есть свой стейт), либо тупыми (управляются родителём). В данном случае isActive управляется родителем, поэтому необходимо дополнительно в props-ах добавить callback setActive и использовать его тут.

2023-08-09 09:53 UTC, bin-umar commented
Не все комментарии пофикшены. А именно 
- https://github.com/ilinaro/GROK/pull/44/files#r1288232656
- https://github.com/ilinaro/GROK/pull/44/files#r1275563463
- Оставил пару новых.

Также не ответили на мой предыдущий вопрос:
> Приведите пример гипотетического кейса в котором в будущем будете слать реальные уведомления.

2023-08-09 09:53 UTC, bin-umar requested changes
Не все комментарии пофикшены. А именно 
- https://github.com/ilinaro/GROK/pull/44/files#r1288232656
- https://github.com/ilinaro/GROK/pull/44/files#r1275563463
- Оставил пару новых.

Также не ответили на мой предыдущий вопрос:
> Приведите пример гипотетического кейса в котором в будущем будете слать реальные уведомления.

2023-08-09 12:55 UTC, err415 commented
> 
Использую напрямую Notification API в компонентах:
CreateForm и comments.
Сразу вызываю new Notification("Убрал ненужные компоненты")

2023-08-09 14:03 UTC, bin-umar commented on packages/client/src/fuature/forum/layouts/ForumLayout/ForumLayout.tsx
> +import { NotificationAPI } from '../../components/notification';
Забыл убрать?

2023-08-09 14:08 UTC, bin-umar commented
> Использую напрямую Notification API в компонентах: CreateForm и comments. Сразу вызываю new Notification("Убрал ненужные компоненты")

@err415 какую проблему пытаешься этим решить?
Прежде чем отправить уведомление, необходимо сначала спрашивать разрешение (или ж проверить что они есть), что ты правильно и делал в предыдущих работах, но почему удалил не понятно. Тебе следовало всего лишь чуть расширить, а не всё стереть.

2023-08-09 20:55 UTC, err415 commented
> > Использую напрямую Notification API в компонентах: CreateForm и comments. Сразу вызываю new Notification("Убрал ненужные компоненты")
> 
> @err415 какую проблему пытаешься этим решить?  Прежде чем отправить уведомление, необходимо сначала спрашивать разрешение (или ж проверить что они есть), что ты правильно и делал в предыдущих работах, но почему удалил не понятно. Тебе следовало всего лишь чуть расширить, а не всё стереть.

Сдать задание.

Так как по заданию:  - "Добавить минимум одно из описанных в уроках Web API: - Fullscreen API, - Geolocation API, - Perfomance API, - Notification API.". В задании функционал не был описан. Просто добавить. Поэтому я не понимаю ничего на данный момент. И просто добавил Web API.

2023-08-10 00:41 UTC, bin-umar commented
@err415 пойми меня правильно, у меня не стоит задача обесценивать твою работу. Задача стояло в небольшом доработке твоего решения. Поэтому давай с тобой поступим следующее:
- Вернём всё что было (git revert)
- Перенесём notify функцию из NotificationAPI в новый хук (назовём его useNotification)
- Используем useNotification в NotificationAPI, CreateForm и comments

И прощу удалить `await`, если используешь `.then()`.

Договорились? Если что-то непонятно, тегни меня тут, отвечу.

2023-08-10 13:33 UTC, err415 commented
> * енесём notify функцию из NotificationAPI в новый хук (назовём его useNotification)

@bin-umar видимо, я неправильно вас понял. 

Изменения сделаны.

2023-08-10 18:13 UTC, bin-umar commented on packages/client/src/fuature/forum/components/notification/Notification.tsx
> +    await useNotification("").then(() => {
Как уже просил несколько раз
- https://github.com/ilinaro/GROK/pull/44#discussion_r1288232656
- >И прощу удалить await, если используешь .then().

`.then()` нужен для того чтобы подписаться на асинхронную функцию (или проще говоря на Promise) и сделать что-то после его завершения.
`await` ж позволяет не писать колбеки и писать код читабельнее. 

Это два подхода обработки промиса, **нельзя их объединить**.

Настоятельно рекомендую прочитать статью https://learn.javascript.ru/async-await и исправить это.

2023-08-10 18:13 UTC, bin-umar commented on packages/client/src/fuature/forum/components/notification/Notification.tsx
> +    <>
Можно обойтись и без него, лишние скобки.

2023-08-10 18:14 UTC, bin-umar commented on packages/client/src/fuature/forum/components/notification/components/Alert/Alert.tsx
> +  })
@err415 ?

2023-08-10 18:14 UTC, bin-umar commented on packages/client/src/fuature/forum/components/notification/components/Alert/Alert.tsx
> +        <div className={ styles.close_btn } onClick={ () => !isActive }></div>
@err415 на это тоже стоит обратить внимание.

2023-08-10 19:07 UTC, bin-umar commented on packages/client/src/fuature/forum/hooks/useNotification.tsx
> +}
хуки чуть сложнее обычных функций, их нельзя вызывать везде где хочеться. Например такая конструкция неправильная:
```tsx
<AlertButton type="success" onClick={ () => useNotification("") }>Проверить</AlertButton>
```
потому что ты вызывешь хук внутри onClick, что не правильно (так задумано разработчиками react, и даже будет [ругаться](https://legacy.reactjs.org/warnings/invalid-hook-call-warning.html)).

Поэтому правильнее делать так:
```suggestion
export function useNotification() {
  function notify(text: string) {
    if (!("Notification" in window)) {
      alert("Браузер не поддерживает уведомления!")
    } else if (Notification.permission === "granted") {
      new Notification(Text);
    } else if (Notification.permission !== "denied") {
      Notification.requestPermission().then((permission) => {
        if (permission === "granted") {
          new Notification(text);
        }
      });
    }
  }

  return { notify };
}
```

Место вызовы:
```tsx
const { notify } = useNotification();

<AlertButton type="success" onClick={ () => notify("") }>Проверить</AlertButton>
```

2023-08-10 19:15 UTC, bin-umar commented
@err415 Привет!
Осталось чуть-чуть). Прощу пофиксить последние пару комментов:
- Всё таки не до конца починить await и .then()
- Небольшой косяк с новым хуком.

2023-08-11 06:27 UTC, bin-umar commented on packages/client/src/fuature/forum/components/notification/Notification.tsx
> +    await notify("")
Это не асинхронная функция :)

2023-08-11 06:27 UTC, bin-umar approved these changes

2023-08-11 19:28 UTC, merged