49 redux router ssr
ilinaro/GROK pull request #50
Opened 2023-08-19 14:48 UTC by bulgakovd97

### Какую задачу решаем
Добавление Redux (начального состояния стора) и роутинга в SSR

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-08-19 18:08 UTC, ilyakaverin approved these changes

2023-08-20 10:10 UTC, AlexSm0ke approved these changes

2023-08-20 15:40 UTC, Olegas requested changes
Добрый день.
Многочисленные замечания по коду. Написал комментарии в конкретных местах с проблемами.
Хочу обратить внимание - не самая хорошая практика вместе с задачей нести рефакторинг на 77к измененных строк. Рефакторинг - хорошо, но его надо нести в репозиторий отдельно. А при сдаче задачи в зачет в PR лучше оставить только саму задачу.
Еще один момент который бросился в глаза - очень много кода, который просто закомментирован и оставлен в таком состоянии. Так быть не должно. Каждый новый PR не должен урезать функциональность приложения а должен развивать и улучшать ее.

2023-08-20 15:40 UTC, Olegas commented on lerna-debug.log
> +3 error     at callbackError (C:\Users\PtitsynAA\Documents\YandexMiddleFrontend\Module2\GROK\node_modules\agent-base\dist\src\index.js:136:17)
Не надо комитить логи в репозиторий проекта

2023-08-20 15:40 UTC, Olegas commented on packages/client/src/App.tsx
> +      {/* SSR */}
Не надо оставлять в проекте закомментированный код

2023-08-20 15:40 UTC, Olegas commented on packages/client/src/components/design-system/SVG/AvatarSVG/AvatarSVG.tsx
> +  // const currentColor = useGetCSSVars('color', color);
Не надо оставлять закомментированный код

2023-08-20 15:40 UTC, Olegas commented on packages/client/src/fuature/forum/components/fullscreen/FullScreen.tsx
> +    if (typeof document !== 'undefined') {
Для чего здесь добавлена проверка? Ведь это обработчик события мыши. На сервере при построении он точно не произойдет

2023-08-20 15:40 UTC, Olegas commented on packages/client/src/fuature/game/Game.tsx
> +      {typeof window === 'undefined' && <canvas ref={canvasRef} />}
Такая проверка скорее всего приведет к ошибке гидрации при оживлении приложения. Потому что верстка, посмотренная на сервере будет отличаться от верстки, построенной на клиенте

2023-08-20 15:40 UTC, Olegas commented on packages/client/src/fuature/login/components/LoginForm/LoginForm.tsx
> +      {Boolean(error) && <FormError view={'error'} description={error?.response?.data.reason ?? ''} />}
Зачем после error ?. , ведь проверили уже на то что error есть (через Boolean(error))

2023-08-20 15:40 UTC, Olegas commented on packages/client/vite.config.ts.timestamp-1692283728436.mjs
> +import { defineConfig } from "vite";
Это что-то автогенерируемое. Этому точно место в репозитории?

2023-08-20 15:40 UTC, Olegas commented on packages/client/tsconfig.paths.json
> +        "./fuature/*"
Опечатка в слове feature

2023-08-20 15:40 UTC, Olegas commented on packages/client/ssr-dist/ssr.cjs
Папка ssr-dist - это же результат сборки приложения. Не надо это комитить в репозиторий.

2023-08-20 15:40 UTC, Olegas commented on packages/client/src/store/index.ts
> +          ignoredActionPaths: ['payload'],
Для чего потребовалось отключать проверку на сериализацию здесь? Если это действительно нужно - лучше зафиксировать реальную причину в комментарии

2023-08-20 15:40 UTC, Olegas commented on packages/client/src/routes/SSRRoutes.tsx
> +  } = useQuery(['user'], async () => await authApi.getCurrentUser(), {
Зачем тут async/await? Достаточно просто вернуть то, что возвращает getCurrentUser

2023-08-20 15:40 UTC, Olegas commented on packages/client/src/pages/start/StartPage.tsx
> +  return <>{/* {(typeof window !== 'undefined') && <Start />} */}</>;
Тут что-то странное. Из компонента пропало все полезное, осталась одна пустоту. Почему так?

2023-08-20 15:40 UTC, Olegas commented on packages/client/src/pages/game/GamePage.tsx
> +  <GameLayout>{/* {typeof window !== 'undefined' && <Game />} */}</GameLayout>
Еще одно место, где убрали компонент и ничем не заменили.

2023-08-20 15:40 UTC, Olegas commented on packages/client/src/lib/useGetUserQuery.ts
> +  return useQuery(['user'], async () => await authApi.getCurrentUser(), {
Зачем async await тут? Достаточно просто вернуть то, что вернет getUser

2023-08-20 15:40 UTC, Olegas commented on packages/client/src/lib/useAuthQuery.ts
> +      await authApi.logout();
Лишний await - тут, и еще 2 функции выше

2023-08-20 15:40 UTC, Olegas commented on packages/client/src/layouts/ProfileLayout/ProfileLayout.tsx
> +          </ErrorBoundary> */}
Почему убрали ErrorBoundary?

2023-08-20 16:53 UTC, bulgakovd97 commented on packages/client/tsconfig.paths.json
> +        "./fuature/*"
Как вы верно заметили, было ошибкой совмещать в одном ПР новую задачку и некоторый рефакторинг.
В данном случае, если я исправлю опечатку в названии папки, то закоммичу более 300 файлов, в которых будут какие-либо изменения.
Думаю, всё же лучше сделать это отдельно.

2023-08-20 16:55 UTC, bulgakovd97 commented on packages/client/src/pages/start/StartPage.tsx
> +  return <>{/* {(typeof window !== 'undefined') && <Start />} */}</>;
К сожалению, не могу точно ответить на ваш вопрос, поскольку компонент был закоммичен до того, как я взялся выполнять свою текущую задачу.
Думаю, что будет лучше разобраться с этим в отдельной ветке.

2023-08-20 16:55 UTC, bulgakovd97 commented on packages/client/src/pages/game/GamePage.tsx
> +  <GameLayout>{/* {typeof window !== 'undefined' && <Game />} */}</GameLayout>
Тут то же самое, что в комментарии выше.

2023-08-20 17:13 UTC, Olegas commented on packages/client/src/pages/start/StartPage.tsx
> +  return <>{/* {(typeof window !== 'undefined') && <Start />} */}</>;
Ну как же, вот изменения, тут компонент Start есть
<img width="1065" alt="image" src="https://github.com/ilinaro/GROK/assets/389390/e0c3c7d6-2719-4171-8865-a2d7a5e360fe">

2023-08-20 17:14 UTC, Olegas commented on packages/client/tsconfig.paths.json
> +        "./fuature/*"
Да, согаласен. Ок, это оставим как есть

2023-08-20 17:15 UTC, Olegas commented on packages/client/src/pages/game/GamePage.tsx
> +  <GameLayout>{/* {typeof window !== 'undefined' && <Game />} */}</GameLayout>
Здесь тоже была реализация
<img width="486" alt="image" src="https://github.com/ilinaro/GROK/assets/389390/8932101a-9d87-4699-abb1-aee7a0463497">

2023-08-20 22:50 UTC, bulgakovd97 commented on packages/client/src/pages/start/StartPage.tsx
> +  return <>{/* {(typeof window !== 'undefined') && <Start />} */}</>;
Да, это бы не мой коммит, просто подтягивал ветку коллеги, которая не была смёржена в ветку девелоп, потому как моя задача была продолжением его задачи.
Тем не менее, пока что пробую разобраться с ошибками при раскомментировании.

2023-08-21 00:29 UTC, bulgakovd97 commented on packages/client/src/pages/start/StartPage.tsx
> +  return <>{/* {(typeof window !== 'undefined') && <Start />} */}</>;
Возникли проблемы с иконками из библиотеки @phosphor-icons/react в SSR.
Поэтому компоненты <Start /> и <Game /> были закомментированы, видимо.
Пока не удаётся их решить, но в остальном redux и роутинг в SSR работают.

2023-08-21 19:03 UTC, Olegas requested changes
Папка ssr-dist по прежнему закомичена в репозиторий. Зачем это нужно? Это же автоматически сгенерированный код.

2023-08-22 12:13 UTC, Olegas approved these changes
Спасибо, работа принята!

2023-09-04 14:00 UTC, merged