56 toggle theme client (Ready for review)
ilinaro/GROK pull request #51
Opened 2023-08-20 17:51 UTC by AlexSm0ke

### Какую задачу решаем
Смена темы приложения

### Скриншоты/видяшка (если есть)
![image](https://github.com/ilinaro/GROK/assets/102740066/f16ac5dc-f595-411e-be99-f6dcb034455e)
![image](https://github.com/ilinaro/GROK/assets/102740066/52fa4da9-3c71-48fb-a54b-818a9df70237)

### TBD (если есть)
В данной задаче реализовал компонент для смены темы приложения, который меняет корневые цвета у html, проверяет системную тему, сохраняет тему в localstorage, а так же отправляет запросы на бэк для чтения и записи.

2023-08-20 19:56 UTC, bulgakovd97 approved these changes

2023-08-21 07:09 UTC, kate-lozovaya reviewed
поправь линтер, посмотри комменты, и призывай еще раз

2023-08-21 07:09 UTC, kate-lozovaya commented on packages/client/src/components/specific/Toggle/ToggleTheme.module.scss
> +	transition: .4s;
Анимации лучше помещать в медиа запрос [`@media (prefers-reduced-motion: no-preference)`](https://doka.guide/a11y/prefers-reduced-motion/) для доступности

2023-08-21 07:09 UTC, kate-lozovaya commented on packages/client/src/styles/_variables.scss
> +	--color-white: #253149;
#253149 - это не белый цвет. Может назвать их нейтрально? Главный цвет, второстепенный и т д?

2023-08-24 08:09 UTC, AlexSm0ke commented on packages/client/src/components/specific/Toggle/ToggleTheme.module.scss
> +	transition: .4s;
Добавил запрос в переключатель. Не совсем понял как в остальном приложении использовать. Нужно обернуть html в такой запрос? Или каждый класс с анимацией нужно оборачивать?

2023-08-24 08:09 UTC, it-ptitsa commented on packages/client/src/styles/_variables.scss
> +	--color-white: #253149;
Исправил. Сделал универсальные названия

2023-08-24 08:38 UTC, kate-lozovaya commented on packages/client/src/components/specific/Toggle/ToggleTheme.module.scss
> +	transition: .4s;
Каждый раз в css нужно оборачивать анимацию

2023-08-24 08:41 UTC, kate-lozovaya requested changes

2023-08-24 08:41 UTC, kate-lozovaya commented on packages/client/src/components/specific/Toggle/ToggleTheme.module.scss
> +@media (prefers-reduced-motion: no-preference) {
в @media (prefers-reduced-motion: no-preference) нужно оборачивать только transition: .4s;, все остальные свойства не нужно. 
Если у пользователя выключена анимация, сейчас нужный css не применится

2023-08-24 08:41 UTC, kate-lozovaya commented
Привывай заново в ревью после правок, чтобы точно было видно, что нужно придти)

2023-08-24 09:08 UTC, AlexSm0ke commented on packages/client/src/components/specific/Toggle/ToggleTheme.module.scss
> +@media (prefers-reduced-motion: no-preference) {
во всем проекте обернул transition в медиазапрос

2023-08-24 09:09 UTC, AlexSm0ke commented
@kate-lozovaya все поправил)

2023-08-24 09:51 UTC, kate-lozovaya approved these changes

2023-08-25 06:42 UTC, merged